<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="9" total="10" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="104" started-at="2017-07-06T04:51:09Z" finished-at="2017-07-06T04:51:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="104" started-at="2017-07-06T04:51:09Z" finished-at="2017-07-06T04:51:09Z">
      <class name="com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest">
        <test-method status="PASS" signature="loadDB()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@5f375618]" name="loadDB" is-config="true" duration-ms="78" started-at="2017-07-06T10:21:09Z" finished-at="2017-07-06T10:21:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadDB -->
        <test-method status="PASS" signature="getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@5f375618]" name="getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name" duration-ms="5" started-at="2017-07-06T10:21:09Z" finished-at="2017-07-06T10:21:09Z">
          <exception class="com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException">
            <message>
              <![CDATA[Individual Object with Name=Individual By This Name Does Not Exist not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException: Individual Object with Name=Individual By This Name Does Not Exist not found
	at com.qainfotech.tap.training.resourceio.TeamsYamlReader.getIndividualByName(TeamsYamlReader.java:84)
	at com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest.getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name(TeamsYamlReaderTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name -->
      </class> <!-- com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
